name: Build and Publish Binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 依存インストール（pkg は devDependencies）
      - name: Install deps
        run: npm ci

      # pkg で Linux x64 バイナリを出力
      - name: Build binary via pkg
        run: npx pkg . --targets node20-linux-x64 --output kenpo-watcher-linux

      # バイナリをアーティファクト化
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: kenpo-watcher-binary   # ← render で参照する artifact 名
          path: kenpo-watcher-linux     # ← ここを実際のファイル名に
