name: Build and Publish Binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build binary via pkg
        run: npm run build-binary
        # → package.json に定義されたスクリプト:
        #   "build-binary": "pkg index.js --targets node20-linux-x64 --output kenpo-watcher-linux"
      - name: Debug: list build output
      　　run: ls -l .

      - name: Upload kenpo-watcher binary
        uses: actions/upload-artifact@v3
        with:
          name: kenpo-watcher-binary   # ← Render 側で参照する artifact name
          path: kenpo-watcher-linux    # ← 実際に出力されたファイル名
