# .github/workflows/build-and-publish.yml
name: Build and Publish Binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) コードをチェックアウト
      - uses: actions/checkout@v3

      # 2) 依存インストール
      - name: Install dependencies
        run: npm install

      # 3) pkg で単一バイナリをビルド
      - name: Build binary via pkg
        run: npm run build-binary
        # → package.json の scripts:
        #    "build-binary": "pkg index.js --targets node20-linux-x64 --output kenpo-watcher-linux"

      # 4) アーティファクトとしてバイナリをアップロード
      - name: Upload kenpo-watcher binary
        uses: actions/upload-artifact@v4
        with:
          name: kenpo-watcher-binary   # ← Render でこれを参照します
          path: kenpo-watcher-linux    # ← pkg の出力ファイル名
