name: Build & Package

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build single binary with pkg
        run: npx pkg . --targets node16-linux-x64 --output kenpo-watcher-linux
      - name: Upload kenpo-watcher binary
        uses: actions/upload-artifact@v3
        with:
          name: kenpo-watcher-binary
          path: kenpo-watcher-linux
